Resonance finder
BlackHolePerturbationToolkit/KerrGeodesics pull request #28
Opened 2022-07-26 15:54 UTC by nielsw2

A few things to do/decide:

- Move the resonance finder code out of KerrGeoOrbit into KerrGeoSpecialOrbits
- Decide on the argument format (association vs different function names). This then also effects whether the output should be a replacement rule or just a number

Other than these two the code looks good to be merged

2022-07-26 20:59 UTC, nielsw2 commented
The code is ready to be merged but we should add some Mathematica documentation for the new ```KerrGeoFindResonance``` function, and also add a unit test or two.

2022-07-28 20:01 UTC, znasipak requested changes
I have a finder function given (a, p, e) that returns x that I can include before the final merge

2022-07-28 20:01 UTC, znasipak commented on Kernel/SpecialOrbits.m
> +\[Pi]p[a_,p_,1,1]:=(-4*Sqrt[p^3*(a^3+a*(-2+p)*p)^2]+2*p*(-a^4+(-4+p)*p^2+a^2*p*(3+p)))/(((a-p)^2-4*p)*(-4*p+(a+p)^2));
Need to replace `a_,p_,1,1` with `a_,p_,e/;e==1,1`

2022-07-28 20:01 UTC, znasipak commented on Kernel/SpecialOrbits.m
> +	If[p<e0Tests || p> e1Test, Message[KerrGeoFindResonance::noresonance, e0Test, e1Test ]; Abort[];];
`e0Test` not `e0Tests`

2022-07-28 20:01 UTC, znasipak commented on Kernel/SpecialOrbits.m
> +	If[a^2>1, Print["Invalid black hole spin parameter. Choose 0 \[LessEqual] a \[LessEqual] 1."]; aFlag=False];
These should be error messages not print statements

2022-07-28 20:07 UTC, znasipak commented on Kernel/SpecialOrbits.m
> +\[Pi]p[a_,p_,1,1]:=(-4*Sqrt[p^3*(a^3+a*(-2+p)*p)^2]+2*p*(-a^4+(-4+p)*p^2+a^2*p*(3+p)))/(((a-p)^2-4*p)*(-4*p+(a+p)^2));
This was resolved in commit e35a01044f0f58761a62d73008f8a8feed7c8c31

2022-07-28 20:07 UTC, znasipak commented on Kernel/SpecialOrbits.m
> +	If[p<e0Tests || p> e1Test, Message[KerrGeoFindResonance::noresonance, e0Test, e1Test ]; Abort[];];
This was resolved in commit e35a01044f0f58761a62d73008f8a8feed7c8c31

2022-07-28 20:08 UTC, znasipak commented on Kernel/SpecialOrbits.m
> +	If[a^2>1, Print["Invalid black hole spin parameter. Choose 0 \[LessEqual] a \[LessEqual] 1."]; aFlag=False];
This was resolved in commit e35a01044f0f58761a62d73008f8a8feed7c8c31

2022-07-28 20:08 UTC, znasipak approved these changes

2022-07-29 13:30 UTC, merged